All: main.cpp TilesAnalysis.cpp ScoreCalc.cpp TaiTable.cpp HuTable.cpp HonorsTable.cpp SimplesTable.cpp Tiles.cpp
	g++-8.2 -std=c++17 -O2 -w -o TilesAnalysis main.cpp TilesAnalysis.cpp ScoreCalc.cpp TaiTable.cpp HuTable.cpp HonorsTable.cpp SimplesTable.cpp Tiles.cpp

Clean:
	rm -f main.out
